//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.NegativeTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NegativeTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NegativeTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.NegativeTests.Negati" +
                            "veTests", typeof(NegativeTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-11-14T04:11:25.2787332Z ##[section]Starting: Run L0/L1 Tests and Post Build Validations
        ///2018-11-14T04:11:25.2792051Z ==============================================================================
        ///2018-11-14T04:11:25.2792149Z Task         : MSBuild
        ///2018-11-14T04:11:25.2792194Z Description  : Build with MSBuild
        ///2018-11-14T04:11:25.2792261Z Version      : 1.120.2
        ///2018-11-14T04:11:25.2792305Z Author       : Microsoft Corporation
        ///2018-11-14T04:11:25.2792390Z Help         : [More Information](https://g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase001 {
            get {
                return ResourceManager.GetString("TestCase001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-11-14T03:57:13.3379679Z ##[section]Starting: Job
        ///2018-11-14T03:57:13.5391343Z ##[section]Starting: Initialize job
        ///2018-11-14T03:57:13.5391574Z Current agent version: &apos;2.142.1&apos;
        ///2018-11-14T03:57:13.5603920Z Prepare build directory.
        ///2018-11-14T03:57:13.5936146Z Set build variables.
        ///2018-11-14T03:57:13.5978242Z Download all required tasks.
        ///2018-11-14T03:57:13.6763808Z ##[section]Finishing: Initialize job
        ///2018-11-14T03:57:13.7210243Z ##[section]Starting: Kill orphan processes
        ///2018-11-14T03:57:13.743 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase002 {
            get {
                return ResourceManager.GetString("TestCase002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-07-01T05:02:41.8147309Z ##[section]Starting: Release
        ///2018-07-01T05:02:41.8167465Z Current agent version: &apos;2.133.3&apos;
        ///2018-07-01T05:02:42.3347263Z ##[section]Starting: Initialize Job
        ///2018-07-01T05:02:42.3422055Z Prepare build directory.
        ///2018-07-01T05:02:42.3781621Z Set build variables.
        ///2018-07-01T05:02:42.3822038Z Download all required tasks.
        ///2018-07-01T05:02:42.4426386Z ##[section]Finishing: Initialize Job
        ///2018-07-01T05:02:42.4870743Z ##[section]Starting: Get Sources
        ///2018-07-01T05:02:42.5223991Z  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase003 {
            get {
                return ResourceManager.GetString("TestCase003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-11-14T00:31:54.6991294Z ##[section]Starting: Deploy MDS
        ///2018-11-14T00:31:54.6995549Z ==============================================================================
        ///2018-11-14T00:31:54.6995820Z Task         : DeployMds
        ///2018-11-14T00:31:54.6996141Z Description  : Installs and ensures that a Rolling oriented implemention of the MDS Monitoring Agent is running. Data pushed to VSODev\Rolling Kusto Database
        ///2018-11-14T00:31:54.6996597Z Version      : 3.0.0
        ///2018-11-14T00:31:54.6996788Z Author       : SI  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase004 {
            get {
                return ResourceManager.GetString("TestCase004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_fail1
        ///test_fail1 contains multiple lines
        ///FThis is output for test_fail2
        ///FFThis is output for test_pass4
        ///FThis is output for test_pass1
        ///test_pass1 contains multiple lines
        ///.This is output for test_pass2
        ///..ssThis is output for test_split
        ///test_split contains multiple lines
        ///.
        ///======================================================================
        ///FAIL: test_fail (__main__.TestStringMethods)
        ///----------------------------------------------------------------------
        ///Traceback (most  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase005 {
            get {
                return ResourceManager.GetString("TestCase005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_pass1 test_pass1 contains multiple lines .This is output for test_pass2
        ///..This is output for test_split
        ///test_split contains multiple lines
        ///.
        ///----------------------------------------------------------------------
        ///
        ///Ran 4 tests in 0.002s
        ///
        ///OK.
        /// </summary>
        internal static string TestCase006 {
            get {
                return ResourceManager.GetString("TestCase006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_expectedFail
        ///test_expectedFail contains multiple lines
        ///xThis is output for test_expectedFail2
        ///test_expectedFail2 contains multiple lines
        ///xThis is output for test_pass1 test_pass1 contains multiple lines .This is output for test_pass2
        ///..ssThis is output for test_split
        ///test_split contains multiple lines
        ///.
        ///----------------------------------------------------------------------
        ///
        ///Ran 8 tests in 0.004s
        ///
        ///OK (skipped=2, expected failures=2).
        /// </summary>
        internal static string TestCase007 {
            get {
                return ResourceManager.GetString("TestCase007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///ageitgey / face_recognition
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #10
        /// 
        ///Job #10.3
        /// More options
        /// master build
        /// Commit 8798dec 
        /// Compare 751f060..8798dec 
        /// Branch master 
        /// Adam Geitgey avatar Adam Geitgey
        ///
        /// #10.3 failed
        /// Ran for 7 min 42 sec
        /// 2 years ago
        /// Python: 3.5
        ///Job log
        /// 
        ///View config [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase008 {
            get {
                return ResourceManager.GetString("TestCase008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///ageitgey / face_recognition
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #87
        /// 
        ///Job #87.4
        /// More options
        /// parallel-processing All support for parallel processing in the CLI
        /// Commit d172081 
        /// Compare d172081ad589 
        /// Branch parallel-processing 
        /// Adam Geitgey avatar Adam Geitgey
        ///
        /// #87.4 failed
        /// Ran for 8  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase009 {
            get {
                return ResourceManager.GetString("TestCase009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///ageitgey / face_recognition
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #245
        /// 
        ///Job #245.5
        /// More options
        /// master Link to chinese readme
        /// Commit b9e5ad2 
        /// Compare 50c0ac7..b9e5ad2 
        /// Branch master 
        /// Adam Geitgey avatar Adam Geitgey
        ///
        /// #245.5 passed
        /// Ran for 17 min 35 sec
        /// 14 days ago
        /// Python: 3.7
        ///Jo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase010 {
            get {
                return ResourceManager.GetString("TestCase010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///faif / python-patterns
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #187
        /// 
        ///Job #187.1
        /// More options
        /// master Update .travis.yml
        ///Remove python 3.3
        ///
        /// Commit f1e5924 
        /// Compare d3bd0d8..f1e5924 
        /// Branch master 
        /// Sakis Kasampalis avatar Sakis Kasampalis
        ///
        /// #187.1 passed
        /// Ran for 1 min 3 sec
        /// 16 days ago [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase011 {
            get {
                return ResourceManager.GetString("TestCase011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_expectedFail
        ///test_expectedFail contains multiple lines
        ///This is output for test_expectedFail2
        ///test_expectedFail2 contains multiple lines
        ///This is output for test_fail1
        ///test_fail1 contains multiple lines
        ///This is output for test_fail2
        ///This is output for test_pass4 This is output for test_pass1 test_pass1 contains multiple lines This is output for test_pass2
        ///This is output for test_split
        ///test_split contains multiple lines
        ///========================================================= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase012 {
            get {
                return ResourceManager.GetString("TestCase012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_pass1 test_pass1 contains multiple lines This is output for test_pass2
        ///This is output for test_split
        ///test_split contains multiple lines
        ///----------------------------------------------------------------------
        ///
        ///Ran 4 tests in 0.002s
        ///
        ///OK.
        /// </summary>
        internal static string TestCase013 {
            get {
                return ResourceManager.GetString("TestCase013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is output for test_expectedFail
        ///test_expectedFail contains multiple lines
        ///This is output for test_expectedFail2
        ///test_expectedFail2 contains multiple lines
        ///This is output for test_pass1 test_pass1 contains multiple lines This is output for test_pass2
        ///This is output for test_split
        ///test_split contains multiple lines
        ///----------------------------------------------------------------------
        ///
        ///Ran 8 tests in 0.005s
        ///
        ///OK (skipped=2, expected failures=2).
        /// </summary>
        internal static string TestCase014 {
            get {
                return ResourceManager.GetString("TestCase014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_fail (__main__.TestStringMethods) ... This is output for test_fail1
        ///test_fail1 contains multiple lines
        ///FAIL
        ///test_fail2 (__main__.TestStringMethods) ... This is output for test_fail2
        ///FAIL
        ///test_fail3 (__main__.TestStringMethods) ... FAIL
        ///test_fail4 (__main__.TestStringMethods) ... This is output for test_pass4
        ///FAIL
        ///test_pass (__main__.TestStringMethods) ... This is output for test_pass1
        ///test_pass1 contains multiple lines
        ///ok
        ///test_pass2 (__main__.TestStringMethods) ... This is output for test_pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase015 {
            get {
                return ResourceManager.GetString("TestCase015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_pass (__main__.TestStringMethods) ... This is output for test_pass1 test_pass1 contains multiple lines ok
        ///test_pass2 (__main__.TestStringMethods) ... This is output for test_pass2
        ///ok
        ///test_pass3 (__main__.TestStringMethods) ... ok
        ///test_split (__main__.TestStringMethods) ... This is output for test_split
        ///test_split contains multiple lines
        ///ok
        ///
        ///----------------------------------------------------------------------
        ///
        ///Ran 4 tests in 0.002s
        ///
        ///OK.
        /// </summary>
        internal static string TestCase016 {
            get {
                return ResourceManager.GetString("TestCase016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_expectedFail (__main__.TestStringMethods) ... This is output for test_expectedFail
        ///test_expectedFail contains multiple lines
        ///expected failure
        ///test_expectedFail2 (__main__.TestStringMethods) ... This is output for test_expectedFail2
        ///test_expectedFail2 contains multiple lines
        ///expected failure
        ///test_pass (__main__.TestStringMethods) ... This is output for test_pass1 test_pass1 contains multiple lines ok
        ///test_pass2 (__main__.TestStringMethods) ... This is output for test_pass2
        ///ok
        ///test_pass3 (__main [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase017 {
            get {
                return ResourceManager.GetString("TestCase017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///Valloric / YouCompleteMe
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #2956
        /// 
        ///Job #2956.2
        /// More options
        /// master Auto merge of #3125 - micbou:omnifunc-invalid-start-column, r=micbou
        ///[READY] Improve omnifunc compliance when start column is invalid
        ///
        ///Contrarily to [what the docs say](https://github.com/vim/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase018 {
            get {
                return ResourceManager.GetString("TestCase018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///Valloric / YouCompleteMe
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #3004
        /// 
        ///Job #3004.1
        /// More options
        /// auto Auto merge of #3104 - micbou:omnifunc-convert-strings-dictionaries, r=micbou
        ///[READY] Convert strings from omnifunc into dictionaries
        ///
        ///Vim allows each item of the list returned by an omnifunc to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase019 {
            get {
                return ResourceManager.GetString("TestCase019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///Valloric / YouCompleteMe
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #3028
        /// 
        ///Job #3028.2
        /// More options
        /// master Merge pull request #3209 from santosh/docs
        ///removes repetitive line
        ///
        /// Commit faa019a 
        /// Compare f67e5ff..faa019a 
        /// Branch master 
        ///  avatar micbou
        ///
        /// #3028.2 passed
        /// Ran for 5 min 59 sec
        /// 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase020 {
            get {
                return ResourceManager.GetString("TestCase020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///rg3 / youtube-dl
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #16435
        /// 
        ///Job #16435.7
        /// More options
        /// master [frontendmasters] Fix issues and improve extraction (closes #3661, closes #16328)
        /// Commit 49128b5 
        /// Compare 4742150..49128b5 
        /// Branch master 
        /// Sergey M. avatar Sergey M.
        ///
        /// #16435.7 failed
        /// Ran f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase021 {
            get {
                return ResourceManager.GetString("TestCase021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///rg3 / youtube-dl
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #16974
        /// 
        ///Job #16974.7
        /// More options
        /// master [zattoo] Arrange API hosts for derived extractors (closes #18035)
        /// Commit 16d896b 
        /// Compare 22e07ce..16d896b 
        /// Branch master 
        /// Sergey M. avatar Sergey M.
        ///
        /// #16974.7 failed
        /// Ran for 1 min 8 sec
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase022 {
            get {
                return ResourceManager.GetString("TestCase022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travis CI
        ///About Us
        /// 
        ///Blog
        /// 
        ///Status
        /// 
        ///Documentation
        /// Sign in with GitHub
        ///Help make Open Source a better place and start building better software today!
        ///
        ///rg3 / youtube-dl
        /// build:passed
        ///Current
        /// 
        ///Branches
        /// 
        ///Build History
        /// 
        ///Pull Requests
        /// 
        ///Build #16999
        /// 
        ///Job #16999.7
        /// More options
        /// master [picarto] Extract more metadata (closes #16518)
        /// Commit 730c0d1 
        /// Compare 83852e5..730c0d1 
        /// Branch master 
        /// Sergey M. avatar Sergey M.
        ///
        /// #16999.7 passed
        /// Ran for 1 min 20 sec
        /// 3 days ago
        /// Pyt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase023 {
            get {
                return ResourceManager.GetString("TestCase023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSJest
        ///&gt; jest
        ///
        /// FAIL  unit_tests/sample.test.js (7.702s)
        ///  ● first set › Test method 2
        ///
        ///    expect(received).toBe(expected) // Object.is equality
        ///
        ///    Expected: false
        ///    Received: true
        ///
        ///      16 |
        ///      17 |     test(&apos;Test method 2&apos;, () =&gt; {
        ///    &gt; 18 |         expect(true).toBe(false);
        ///         |                      ^
        ///      19 |     });
        ///      20 |
        ///      21 |     test(&apos;Test method 3&apos;, () =&gt; {
        ///
        ///      at Object.toBe (unit_tests/sample.test. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase024 {
            get {
                return ResourceManager.GetString("TestCase024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to npm WARN npm npm does not support Node.js v11.0.0
        ///npm WARN npm You should probably upgrade to a newer version of node as we
        ///npm WARN npm can&apos;t make any promises that npm will work with this version.
        ///npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
        ///npm WARN npm You can find the latest version at https://nodejs.org/
        ///&gt; redux@4.0.1 examples:lint /home/travis/build/reduxjs/redux
        ///&gt; eslint examples
        ///Warning: React version not specified in eslint-plugin-react settings. See h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase025 {
            get {
                return ResourceManager.GetString("TestCase025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; redux@3.7.2 prepare /home/travis/build/reactjs/redux
        ///&gt; npm run clean &amp;&amp; npm run lint &amp;&amp; npm test &amp;&amp; npm run build
        ///&gt; redux@3.7.2 clean /home/travis/build/reactjs/redux
        ///&gt; rimraf lib dist es coverage
        ///&gt; redux@3.7.2 lint /home/travis/build/reactjs/redux
        ///&gt; eslint src test build
        ///&gt; redux@3.7.2 test /home/travis/build/reactjs/redux
        ///&gt; cross-env BABEL_ENV=commonjs jest
        /// PASS  test/utils/warning.spec.js
        /// PASS  test/combineReducers.spec.js (5.632s)
        /// PASS  test/compose.spec.js (5.748s)
        /// PASS  test/bindAction [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase026 {
            get {
                return ResourceManager.GetString("TestCase026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/bash -eo pipefail
        ///# Limit maxWorkers to 3 to avoid OOM on CircleCI
        ///yarn test-only --maxWorkers 3
        ///yarn run v1.9.4
        ///$ node --max_old_space_size=4096 node_modules/jest/bin/jest.js --verbose --maxWorkers 3
        /// PASS  __tests__/registries/npm-registry.js
        ///  normalizeConfig
        ///    ✓ environment is replaced (35ms)
        ///    ✓ path normalization doesn&apos;t affect all options (1ms)
        ///    ✓ resolve path to current directory (16ms)
        ///    ✓ resolve path to home directory
        ///    ✓ resolve keep path to rooted directory
        ///    ✓ h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase027 {
            get {
                return ResourceManager.GetString("TestCase027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/bash -eo pipefail
        ///# Limit maxWorkers to 3 to avoid OOM on CircleCI
        ///yarn test-only --maxWorkers 3
        ///^D^Dyarn run v1.1.0
        ///$ node --max_old_space_size=4096 node_modules/jest/bin/jest.js --verbose &quot;--maxWorkers&quot; &quot;3&quot;
        /// PASS  __tests__/registries/npm-registry.js (5.615s)
        ///  normalizeConfig
        ///    ✓ environment is replaced (111ms)
        ///    ✓ path normalization doesn&apos;t affect all options (1ms)
        ///    ✓ resolve path to current directory (43ms)
        ///    ✓ resolve path to home directory
        ///    ✓ resolve keep path to roo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase028 {
            get {
                return ResourceManager.GetString("TestCase028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/bash -eo pipefail
        ///# Limit maxWorkers to 3 to avoid OOM on CircleCI
        ///yarn test-only --maxWorkers 3
        ///^D^Dyarn run v1.1.0
        ///warning You are using Node &quot;10.12.0&quot; which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: &quot;^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0&quot;
        ///(node:5862) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase029 {
            get {
                return ResourceManager.GetString("TestCase029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 386.63s$ yarn travis:$JOB_PART
        ///yarn run v1.3.2
        ///(node:3973) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
        ///$ yarn cover:init &amp;&amp; yarn cover:integration --ci $JEST
        ///(node:3995) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
        ///$ rimraf coverage
        ///(node: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase030 {
            get {
                return ResourceManager.GetString("TestCase030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +../node_modules/.bin/jest -w 2
        /// PASS  fixtures/mjs-support/index.test.js (119.724s)
        /// PASS  fixtures/webpack-message-formatting/index.test.js (140.943s)
        /// PASS  fixtures/relative-paths/index.test.js (37.807s)
        /// FAIL  fixtures/typescript-advanced/index.test.js (70.498s)
        ///  ● builds in development
        ///    expect(received).toBe(expected) // Object.is equality
        ///    Expected: true
        ///    Received: false
        ///      3 | test(&apos;builds in development&apos;, async () =&gt; {
        ///      4 |   const { fulfilled, ...rest } = await testSetu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase031 {
            get {
                return ResourceManager.GetString("TestCase031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned up the lib folder.
        ///Compiling iframeScript.js
        ///Hash: 974491276ad7d64f31fc
        ///Time: 8927ms
        ///Built at: 10/22/2018 10:14:58 PM
        ///           Asset     Size  Chunks             Chunk Names
        ///iframe-bundle.js  259 KiB       0  [emitted]  main
        ///Entrypoint main = iframe-bundle.js
        ///Compiling index.js
        ///Hash: 6205dfdf0e7167fe2172
        ///Time: 854ms
        ///Built at: 10/22/2018 10:14:59 PM
        ///   Asset     Size  Chunks                    Chunk Names
        ///index.js  310 KiB       0  [emitted]  [big]  main
        ///Entrypoint main [big] = index. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase032 {
            get {
                return ResourceManager.GetString("TestCase032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &quot;if [ $TEST_SUITE = &quot;simple&quot; ]; then tasks/e2e-simple.sh; fi&quot; exited with 0.
        ///0.00s$ if [ $TEST_SUITE = &quot;installs&quot; ]; then tasks/e2e-installs.sh; fi
        ///The command &quot;if [ $TEST_SUITE = &quot;installs&quot; ]; then tasks/e2e-installs.sh; fi&quot; exited with 0.
        ///0.00s$ if [ $TEST_SUITE = &quot;kitchensink&quot; ]; then tasks/e2e-kitchensink.sh; fi
        ///The command &quot;if [ $TEST_SUITE = &quot;kitchensink&quot; ]; then tasks/e2e-kitchensink.sh; fi&quot; exited with 0.
        ///173.48s$ if [ $TEST_SUITE = &quot;kitchensink-eject&quot; ]; then tasks/e2e-kitchensink- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase033 {
            get {
                return ResourceManager.GetString("TestCase033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\oneOf.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\pattern.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\properties.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\propertyNames.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\ref.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ajv\\lib\\dotjs\\required.js&apos;,
        ///  &apos;node_modules\\har-validator\\node_modules\\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase034 {
            get {
                return ResourceManager.GetString("TestCase034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSJest
        ///&gt; jest
        ///
        /// FAIL  unit_tests/sample.test.js
        ///  ● first set › Test method 1
        ///
        ///    expect(received).toBe(expected) // Object.is equality
        ///
        ///    Expected: false
        ///    Received: true
        ///
        ///       7 |
        ///       8 |     beforeEach(() =&gt; {
        ///    &gt;  9 |         expect(true).toBe(false);
        ///         |                      ^
        ///      10 |     })
        ///      11 |
        ///      12 |     test(&apos;Test method 1&apos;, () =&gt; {
        ///
        ///      at Object.toBe (unit_tests/sample.test.js:9:22)
        ///
        ///  ● first [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase035 {
            get {
                return ResourceManager.GetString("TestCase035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ node --version
        ///v10.12.0
        ///$ npm --version
        ///6.4.1
        ///$ nvm --version
        ///0.33.11
        ///$ yarn --version
        ///1.3.2
        ///before_install
        ///0.00s$ if [ &quot;$NODEJS_VERSION&quot; != &quot;&quot; ];
        ///  then
        ///    mkdir /opt/node
        ///    curl --silent &quot;https://nodejs.org/download/nightly/$NODEJS_VERSION/node-$NODEJS_VERSION-linux-x64.tar.gz&quot; | tar -zxf - --directory /opt/node
        ///    export PATH=&quot;/opt/node/node-$NODEJS_VERSION-linux-x64/bin:$PATH&quot;
        ///    node --version
        ///  fi
        ///  
        ///install.1
        ///6.23s$ yarn --frozen-lockfile $YARN_EXTRA_ARGS
        ///yarn install v1.3.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase036 {
            get {
                return ResourceManager.GetString("TestCase036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-25T16:02:57.3534062Z ##[section]Starting: Run tests with coverage
        ///2018-10-25T16:02:57.3538149Z ==============================================================================
        ///2018-10-25T16:02:57.3538229Z Task         : Command Line
        ///2018-10-25T16:02:57.3538307Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-25T16:02:57.3538360Z Version      : 2.142.1
        ///2018-10-25T16:02:57.3538408Z Author       : Microsoft Corporation
        ///2018-10-25T16:02:57.35384 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase037 {
            get {
                return ResourceManager.GetString("TestCase037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJsJasmine
        ///&gt; jasmine --random=false &quot;.\unit_tests\*spec.js&quot;
        ///
        ///Started
        ///*F.F..F.F.
        ///
        ///Failures:
        ///1) first set Test method 2
        ///  Message:
        ///    Expected true to be false.
        ///  Stack:
        ///    Error: Expected true to be false.
        ///        at &lt;Jasmine&gt;
        ///        at UserContext.it (D:\OwnedRepos\NodeJsJasmine\unit_tests\sample_spec.js:18:22)
        ///        at &lt;Jasmine&gt;
        ///
        ///2) first set Test method 4
        ///  Message:
        ///    Expected true to be false.
        ///  Stack:
        ///    Error: Expected true to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase038 {
            get {
                return ResourceManager.GetString("TestCase038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ rvm use 2.5 --install --binary --fuzzy
        ///curl: (22) The requested URL returned error: 404 Not Found
        ///Required ruby-2.5.1 is not installed - installing.
        ///curl: (22) The requested URL returned error: 404 Not Found
        ///Searching for binary rubies, this might take some time.
        ///Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.5.1.tar.bz2
        ///Checking requirements for ubuntu.
        ///Requirements installation successful.
        ///ruby-2.5.1 - #configure
        ///ruby-2.5.1 - #download
        ///  % Total    % Received % Xferd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase039 {
            get {
                return ResourceManager.GetString("TestCase039", resourceCulture);
            }
        }
    }
}
