jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --configuration $(buildConfiguration) --logger:trx --collect "code coverage"
      displayName: 'dotnet test tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --configuration $(buildConfiguration) --logger:trx
      displayName: 'dotnet test tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --configuration $(buildConfiguration) --logger:trx
      displayName: 'dotnet test tests\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2