jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --settings "$(System.DefaultWorkingDirectory)\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.runsettings" --configuration $(buildConfiguration) --logger:trx
      displayName: 'dotnet test Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'
        publishRunAttachments: true
        testRunTitle: 'Windows'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --settings "$(System.DefaultWorkingDirectory)\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.runsettings" --configuration $(buildConfiguration) --logger:trx
      displayName: 'dotnet test Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Mac'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
      buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - script: dotnet test "Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj" --settings "$(System.DefaultWorkingDirectory)\Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.runsettings" --configuration $(buildConfiguration) --logger:trx
      displayName: 'dotnet test Agent.Plugins.UnitTests\Agent.Plugins.UnitTests.csproj --configuration $(buildConfiguration)'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Linux'
