//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.SuccessScenarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessScenarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessScenarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.SuccessScenarios.Suc" +
                            "cessScenarios", typeof(SuccessScenarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [14:43:06] Using gulpfile D:\OwnedRepos\NodeJSTestSuite\gulpfile.js
        ///[14:43:06] Starting &apos;unittest&apos;...
        ///
        ///&gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSTestSuite
        ///&gt; mocha &quot;unit_tests/*.js&quot;
        ///
        ///
        ///
        ///  sampleUnitTests
        ///hey
        ///    ΓêÜ Test method 1)
        ///hoy
        ///    1) Test method 2
        ///    ΓêÜ Test method 3
        ///    2) Test method 4
        ///    - Test method 5
        ///
        ///
        ///  2 passing (9ms)
        ///  1 pending
        ///  2 failing
        ///
        ///  1) sampleUnitTests
        ///       Test method 2:
        ///     Error: done() invoked with non-Error: You have failed
        ///      at Cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase001 {
            get {
                return ResourceManager.GetString("TestCase001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///2
        ///1
        ///9.
        /// </summary>
        internal static string TestCase001Result {
            get {
                return ResourceManager.GetString("TestCase001Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-15T12:24:20.5437285Z ##[section]Starting: Test with node 6
        ///2018-10-15T12:24:20.5446251Z ==============================================================================
        ///2018-10-15T12:24:20.5446423Z Task         : Command Line
        ///2018-10-15T12:24:20.5446584Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-15T12:24:20.5446731Z Version      : 2.136.0
        ///2018-10-15T12:24:20.5446873Z Author       : Microsoft Corporation
        ///2018-10-15T12:24:20.5447014Z Hel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase002 {
            get {
                return ResourceManager.GetString("TestCase002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213
        ///0
        ///0
        ///180000.
        /// </summary>
        internal static string TestCase002Result {
            get {
                return ResourceManager.GetString("TestCase002Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-15T12:27:32.8370798Z ##[section]Starting: Legacy tests with node 6
        ///2018-10-15T12:27:32.8376236Z ==============================================================================
        ///2018-10-15T12:27:32.8376391Z Task         : Command Line
        ///2018-10-15T12:27:32.8376546Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-15T12:27:32.8376679Z Version      : 2.136.0
        ///2018-10-15T12:27:32.8376931Z Author       : Microsoft Corporation
        ///2018-10-15T12:27:32.8377 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase003 {
            get {
                return ResourceManager.GetString("TestCase003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19
        ///0
        ///0
        ///2000.
        /// </summary>
        internal static string TestCase003Result {
            get {
                return ResourceManager.GetString("TestCase003Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-12T08:50:27.8265328Z ##[section]Starting: Test with node 5
        ///2018-10-12T08:50:27.8269711Z ==============================================================================
        ///2018-10-12T08:50:27.8269880Z Task         : Command Line
        ///2018-10-12T08:50:27.8270035Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-12T08:50:27.8270179Z Version      : 2.136.0
        ///2018-10-12T08:50:27.8270318Z Author       : Microsoft Corporation
        ///2018-10-12T08:50:27.8270460Z Hel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase004 {
            get {
                return ResourceManager.GetString("TestCase004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 639
        ///1
        ///0
        ///540000.
        /// </summary>
        internal static string TestCase004Result {
            get {
                return ResourceManager.GetString("TestCase004Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-12T08:33:03.8772826Z ##[section]Starting: Test with node 6
        ///2018-10-12T08:33:03.8785196Z ==============================================================================
        ///2018-10-12T08:33:03.8785365Z Task         : Command Line
        ///2018-10-12T08:33:03.8785526Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-12T08:33:03.8785680Z Version      : 2.136.0
        ///2018-10-12T08:33:03.8785811Z Author       : Microsoft Corporation
        ///2018-10-12T08:33:03.8785953Z Hel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase005 {
            get {
                return ResourceManager.GetString("TestCase005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 951
        ///1
        ///0
        ///720000.
        /// </summary>
        internal static string TestCase005Result {
            get {
                return ResourceManager.GetString("TestCase005Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-09T23:43:15.8279795Z ##[section]Starting: Test with node 6
        ///2018-10-09T23:43:15.8293234Z ==============================================================================
        ///2018-10-09T23:43:15.8293621Z Task         : Command Line
        ///2018-10-09T23:43:15.8293819Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-09T23:43:15.8293994Z Version      : 2.136.0
        ///2018-10-09T23:43:15.8294260Z Author       : Microsoft Corporation
        ///2018-10-09T23:43:15.8294440Z Hel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase006 {
            get {
                return ResourceManager.GetString("TestCase006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 951
        ///1
        ///0
        ///720000.
        /// </summary>
        internal static string TestCase006Result {
            get {
                return ResourceManager.GetString("TestCase006Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-10T14:11:12.7449110Z ##[section]Starting: Run tests
        ///2018-10-10T14:11:12.7452964Z ==============================================================================
        ///2018-10-10T14:11:12.7453043Z Task         : Command Line
        ///2018-10-10T14:11:12.7453094Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-10T14:11:12.7453175Z Version      : 2.136.0
        ///2018-10-10T14:11:12.7453221Z Author       : Microsoft Corporation
        ///2018-10-10T14:11:12.7453270Z Help       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase008 {
            get {
                return ResourceManager.GetString("TestCase008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 373
        ///1
        ///0
        ///120000.
        /// </summary>
        internal static string TestCase008Result {
            get {
                return ResourceManager.GetString("TestCase008Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-08T21:49:29.2601185Z ##[section]Starting: Run tests
        ///2018-10-08T21:49:29.2603733Z ==============================================================================
        ///2018-10-08T21:49:29.2603877Z Task         : Command Line
        ///2018-10-08T21:49:29.2604184Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-08T21:49:29.2604638Z Version      : 2.136.0
        ///2018-10-08T21:49:29.2604790Z Author       : Microsoft Corporation
        ///2018-10-08T21:49:29.2604951Z Help       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase009 {
            get {
                return ResourceManager.GetString("TestCase009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 453
        ///1
        ///0
        ///120000.
        /// </summary>
        internal static string TestCase009Result {
            get {
                return ResourceManager.GetString("TestCase009Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-08T21:52:29.3516410Z ##[section]Starting: Run tests
        ///2018-10-08T21:52:29.3520518Z ==============================================================================
        ///2018-10-08T21:52:29.3520692Z Task         : Command Line
        ///2018-10-08T21:52:29.3520822Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-08T21:52:29.3520968Z Version      : 2.136.0
        ///2018-10-08T21:52:29.3521098Z Author       : Microsoft Corporation
        ///2018-10-08T21:52:29.3521229Z Help       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase010 {
            get {
                return ResourceManager.GetString("TestCase010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 374
        ///0
        ///0
        ///120000.
        /// </summary>
        internal static string TestCase010Result {
            get {
                return ResourceManager.GetString("TestCase010Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-04T21:27:33.1838714Z ##[section]Starting: Run tests
        ///2018-10-04T21:27:33.1843025Z ==============================================================================
        ///2018-10-04T21:27:33.1843621Z Task         : Command Line
        ///2018-10-04T21:27:33.1843682Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-04T21:27:33.1843760Z Version      : 2.136.0
        ///2018-10-04T21:27:33.1843868Z Author       : Microsoft Corporation
        ///2018-10-04T21:27:33.1843918Z Help       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase011 {
            get {
                return ResourceManager.GetString("TestCase011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 373
        ///1
        ///0
        ///120000.
        /// </summary>
        internal static string TestCase011Result {
            get {
                return ResourceManager.GetString("TestCase011Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; mocha &quot;.\unit_tests\*.js\&quot;
        ///
        ///Terminate batch job (Y/N)? ^C^C^CY
        ///PS D:\OwnedRepos\NodeJSTestSuite&gt; npm test .\unit_tests\*.js
        ///
        ///&gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSTestSuite
        ///&gt; mocha &quot;.\unit_tests\*.js&quot;
        ///
        ///
        ///
        ///  sampleUnitTests
        ///    - Test method 1
        ///    - Test method 2
        ///    - Test method 3
        ///    - Test method 4
        ///    - Test method 5
        ///
        ///
        ///  0 passing (12ms)
        ///  5 pending
        ///
        ///&gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSTestSuite
        ///&gt; mocha &quot;.\unit_tests\*.js&quot;
        ///
        ///
        ///
        ///  sampleUnitTests
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase012 {
            get {
                return ResourceManager.GetString("TestCase012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///5
        ///12
        ///0
        ///2
        ///3
        ///11.
        /// </summary>
        internal static string TestCase012Result {
            get {
                return ResourceManager.GetString("TestCase012Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ npm test
        ///&gt; socket.io@2.1.1 test /home/travis/build/socketio/socket.io
        ///&gt; nyc mocha --reporter spec --slow 200 --bail --timeout 10000 test/socket.io.js
        ///  socket.io
        ///    ✓ should be the same version as client
        ///    set
        ///      ✓ should be able to set ping timeout to engine.io
        ///      ✓ should be able to set ping interval to engine.io
        ///      ✓ should be able to set transports to engine.io
        ///      ✓ should be able to set maxHttpBufferSize to engine.io
        ///      ✓ should be able to set path with setting resource
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase013 {
            get {
                return ResourceManager.GetString("TestCase013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126
        ///0
        ///0
        ///9000.
        /// </summary>
        internal static string TestCase013Result {
            get {
                return ResourceManager.GetString("TestCase013Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.36s$ npm test
        ///&gt; socket.io@2.1.1 test /home/travis/build/socketio/socket.io
        ///&gt; nyc mocha --reporter spec --slow 200 --bail --timeout 10000 test/socket.io.js
        ///  socket.io
        ///    ✓ should be the same version as client
        ///    set
        ///      ✓ should be able to set ping timeout to engine.io
        ///      ✓ should be able to set ping interval to engine.io
        ///      ✓ should be able to set transports to engine.io
        ///      ✓ should be able to set maxHttpBufferSize to engine.io
        ///      ✓ should be able to set path with setting resour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase014 {
            get {
                return ResourceManager.GetString("TestCase014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///2
        ///0
        ///253.
        /// </summary>
        internal static string TestCase014Result {
            get {
                return ResourceManager.GetString("TestCase014Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
        ///$ node --version
        ///v6.10.3
        ///$ npm --version
        ///3.10.10
        ///$ nvm --version
        ///0.33.2
        ///install
        ///39.83s$ npm install 
        ///npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
        ///npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase015 {
            get {
                return ResourceManager.GetString("TestCase015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///0
        ///42
        ///1
        ///1
        ///0
        ///42.
        /// </summary>
        internal static string TestCase015Result {
            get {
                return ResourceManager.GetString("TestCase015Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; express@4.16.3 test-ci /home/travis/build/expressjs/express
        ///&gt; istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --require test/support/env --reporter spec --check-leaks test/ test/acceptance/
        ///  Route
        ///    ✓ should work without handlers
        ///    .all
        ///      ✓ should add handler
        ///      ✓ should handle VERBS
        ///      ✓ should stack
        ///    .VERB
        ///      ✓ should support .get
        ///      ✓ should limit to just .VERB
        ///      ✓ should allow fallthrough
        ///    errors
        ///      ✓ should handle errors via arity 4 fun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase016 {
            get {
                return ResourceManager.GetString("TestCase016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 851
        ///4
        ///0
        ///4000.
        /// </summary>
        internal static string TestCase016Result {
            get {
                return ResourceManager.GetString("TestCase016Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; gulp@4.0.0-alpha.3 test /home/travis/build/gulpjs/gulp
        ///&gt; npm run-script lint &amp;&amp; mocha --reporter spec
        ///&gt; gulp@4.0.0-alpha.3 lint /home/travis/build/gulpjs/gulp
        ///&gt; jshint bin test index.js --reporter node_modules/jshint-stylish/stylish.js --exclude node_modules &amp;&amp; jscs bin test index.js
        ///✔ No problems
        ///No code style errors found.
        ///  gulp output stream
        ///    dest()
        ///  ✓ should return a stream
        ///  ✓ should return a output stream that writes files (40ms)
        ///  ✓ should return a output stream that does not write n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase017 {
            get {
                return ResourceManager.GetString("TestCase017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27
        ///1
        ///0
        ///2000
        ///27
        ///1
        ///0
        ///2000.
        /// </summary>
        internal static string TestCase017Result {
            get {
                return ResourceManager.GetString("TestCase017Result", resourceCulture);
            }
        }
    }
}
