//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Plugins.UnitTests.Parser.Python.Resources.SuccessScenarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PythonSuccessTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PythonSuccessTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agent.Plugins.UnitTests.Parser.Python.Resources.SuccessScenarios.PythonSuccessTes" +
                            "tCases", typeof(PythonSuccessTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_passing (Test1.PythonTestClass) ... I am passing test
        ///some extra lines
        ///
        ///
        ///ok
        ///test_passing2 (Test1.PythonTestClass) ... ok
        ///
        ///Ran 2 tests in 0.006s
        ///
        ///OK.
        /// </summary>
        internal static string TestCase001 {
            get {
                return ResourceManager.GetString("TestCase001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///0
        ///2
        ///0:0:0:0.006.
        /// </summary>
        internal static string TestCase001Result {
            get {
                return ResourceManager.GetString("TestCase001Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_failing (Test1.PythonTestClass) ... FailingTest
        ///FAIL
        ///test_passing (Test1.PythonTestClass) ... I am passing test
        ///ok
        ///test_passing2 (Test1.PythonTestClass) ... ok
        ///
        ///test_failing2 (Test1.PythonTestClass) ... FAIL
        ///
        ///======================================================================
        ///FAIL: test_failing (Test1.PythonTestClass)
        ///----------------------------------------------------------------------
        ///Traceback (most recent call last):
        ///  File &quot;D:\Code\LearningPython\Test1.py&quot;, line 15, in test_failing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase002 {
            get {
                return ResourceManager.GetString("TestCase002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///2
        ///4
        ///0:0:0:0.006.
        /// </summary>
        internal static string TestCase002Result {
            get {
                return ResourceManager.GetString("TestCase002Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_passing (Test1.PythonTestClass) ... I am passing test
        ///some extra lines
        ///
        ///
        ///ok
        ///test_passing (Test1.PythonTestClass) ... skipped
        ///test_failing (Test1.PythonTestClass) ... 
        ///hello world
        ///FAIL
        ///test_passing2 (Test1.PythonTestClass) ... ok
        ///test_failing2 (Test1.PythonTestClass) ... FAIL
        ///
        ///Ran 5 tests in 3.006s
        ///
        ///FAILURE (skipped=1, failure=2).
        /// </summary>
        internal static string TestCase003 {
            get {
                return ResourceManager.GetString("TestCase003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///2
        ///5
        ///0:0:0:3.006.
        /// </summary>
        internal static string TestCase003Result {
            get {
                return ResourceManager.GetString("TestCase003Result", resourceCulture);
            }
        }
    }
}
