//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.DetailedTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailedTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.DetailedTests.Detail" +
                            "edTests", typeof(DetailedTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSTestSuite
        ///&gt; mocha &quot;.\unit_tests\*.js&quot;
        ///
        ///
        ///
        ///  sampleUnitTests
        ///    1) Test method 1
        ///    2) Test method 2
        ///    - Test method 3
        ///    - Test method 4
        ///    - Test method 5
        ///
        ///
        ///  0 passing (11ms)
        ///  3 pending
        ///  2 failing
        ///
        ///  1) sampleUnitTests
        ///       Test method 1:
        ///     Error: the string &quot;error&quot; was thrown, throw an Error :)
        ///
        ///
        ///  2) sampleUnitTests
        ///       Test method 2:
        ///     Error: done() invoked with non-Error: hello
        ///      at Context.&lt;anonymous&gt; ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase001 {
            get {
                return ResourceManager.GetString("TestCase001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed 0
        ///
        ///Failed 2
        ///Test method 1
        ///Test method 2
        ///
        ///Skipped 3
        ///Test method 3
        ///Test method 4
        ///Test method 5.
        /// </summary>
        internal static string TestCase001Result {
            get {
                return ResourceManager.GetString("TestCase001Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-10-15T12:24:20.5437285Z ##[section]Starting: Test with node 6
        ///2018-10-15T12:24:20.5446251Z ==============================================================================
        ///2018-10-15T12:24:20.5446423Z Task         : Command Line
        ///2018-10-15T12:24:20.5446584Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
        ///2018-10-15T12:24:20.5446731Z Version      : 2.136.0
        ///2018-10-15T12:24:20.5446873Z Author       : Microsoft Corporation
        ///2018-10-15T12:24:20.5447014Z Hel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase002 {
            get {
                return ResourceManager.GetString("TestCase002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed 213
        ///Do not sign or zipalign if nothing is selected
        ///Do not align or sign if input single file does not exist
        ///Do not align or sign if input pattern does not match any files
        ///Use jarsigner from PATH before searching in JAVA_HOME
        ///Fail if jarsigner is not on PATH and JAVA_HOME is not set
        ///Fail if ANDROID_HOME is not set
        ///Signing a single file
        ///zipalign a single file
        ///Signing and aligning multiple files
        ///Download keystore file from SecureFile
        ///Validate AzureFileCopy.Utility Get-AzureUtility
        ///Validate A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCase002Result {
            get {
                return ResourceManager.GetString("TestCase002Result", resourceCulture);
            }
        }
    }
}
