//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.DetailedTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailedTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agent.Plugins.UnitTests.MochaTestResultParserTests.Resources.DetailedTests.Detail" +
                            "edTests", typeof(DetailedTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; nodejs-application@0.0.0 test D:\OwnedRepos\NodeJSTestSuite
        ///&gt; mocha &quot;.\unit_tests\*.js&quot;
        ///
        ///
        ///
        ///  sampleUnitTests
        ///    1) Test method 1
        ///    2) Test method 2
        ///    - Test method 3
        ///    - Test method 4
        ///    - Test method 5
        ///
        ///
        ///  0 passing (11ms)
        ///  3 pending
        ///  2 failing
        ///
        ///  1) sampleUnitTests
        ///       Test method 1:
        ///     Error: the string &quot;error&quot; was thrown, throw an Error :)
        ///.
        /// </summary>
        internal static string TestCase001 {
            get {
                return ResourceManager.GetString("TestCase001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed 0
        ///
        ///Failed 2
        ///Test method 1
        ///Test method 2
        ///
        ///Skipped 3
        ///Test method 3
        ///Test method 4
        ///Test method 5.
        /// </summary>
        internal static string TestCase001Result {
            get {
                return ResourceManager.GetString("TestCase001Result", resourceCulture);
            }
        }
    }
}
